trigger:
  branches:
    include:
      - "*"

  paths:
    include:
      - "apps/web/**"
      - "packages/**"
      - "pnpm-lock.yaml"
      - ".azure/pipelines/apps/web/**"
      - ".azure/pipelines/templates/**"

pr:
  branches:
    include:
      - main
      - feature/*

variables:
  appName: "web"
  dockerfile: "apps/$(appName)/Dockerfile"
  buildContext: "."
  containerRegistryServiceConnectionId: ""
  buildTag: $(Build.BuildId)
  vmImage: "ubuntu-latest"

stages:
  - stage: CI
    jobs:
      - job: CI
        pool:
          vmImage: $(vmImage)

        steps:
          - template: ../../templates/build-validations.yaml
            parameters:
              appName: $(appName)

          - template: ../../templates/build-push-image.yaml
            parameters:
              appName: $(appName)
              dockerfile: $(dockerfile)
              buildContext: $(buildContext)
              containerRegistryServiceConnectionId: $(containerRegistryServiceConnectionId)
              buildTag: $(buildTag)
